---
title: "Strengthening Sustainable and Inclusive Analytics Ecosystem for Epidemic Preparedness"
fontsize: 12pt
date: 2024-12-02
institutions:
  - logo: mrcg.svg
format: 
  summit-typst:
    # keep-typ: true
    papersize: a4
    subtitle: Summit 2024, Gambia
    when: December 2-6
    # columns: 2
    margin:
      x: 0cm
      y: 0cm
    # mainfont: "Clash Display Variable"
    # font-paths: fonts
editor: 
  markdown: 
    wrap: 72
---

# Introduction

::: block
<!-- ::: {.block fill="luma(230)" inset="8pt" radius="4pt"} -->

Powered by Data.org, the Epiverse-TRACE project has made substantial
progress toward producing analytics tools aimed at addressing the most
critical questions during epidemics. Currently, up to [fourteen (14)
Epiverse-TRACE
packages](https://epiverse-trace.github.io/etstats/index.html) are
available on [CRAN](https://cran.r-project.org/) This reflects the
results of two years of joint efforts between team members and our user
communities.

Every year, the Epiverse-TRACE team members, along with invited
stakeholders from WHO, Data.org, and various healthcare organizations,
convene to discuss progress, evaluate deliverables, and plan future
activities. The third Epiverse-TRACE annual summit will be held at the
MRC Unit in Fajara, The Gambia from December 2 to 6, 2024, under the
theme: **Strengthening Sustainable and Inclusive Analytics Ecosystem for
Epidemic Preparedness**.

[Data.org](https://data.org)
:::

````{=html}
<!-- ```{=typst}
#pagebreak()
``` -->
````

### Pre Summit Training

```{=typst}
Prior to commence the summit, we have conducted a week-long pre-summit training course on "Outbreak Analytics and Applied Modelling with R" at MRCG, Banjul, The Gambia. The training program was designed to provide participants with practical skills in outbreak data analysis using specialized R packages. This training was facilitated by Epiverse-TRACE members from MRCG, LSHTM, and TRACE-LAC.

#image("/images/presumit_picture.jpg")

The full report about this course is available on zenodo: #link("https://zenodo.org/records/14946723")[Pre-summit Training report].
```

## Openning Ceremony

```{=typst}
// We use `rect` to emphasize the
// area of cells.

#set rect(
  inset: 8pt,
  fill: rgb("e4e5ea"),
  width: 100%,
)

#grid(
  columns: (1fr, 1fr),
  rows: (260pt, 300pt),
  gutter: 0pt,
  rect[The third Epiverse Summit was held in Banjul from the 2nd to the 6th of December under the theme “Strengthening a Sustainable and Inclusive Analytics Ecosystem for Epidemic Preparedness”. This annual flagship event brought together 44 participants, including 6 members of the LSHTM, 4 members from Universidad Javeriana and Universidad de los Andes in Colombia, 6 members from the MRC Unit The Gambia, and 5 members of data.org. The discussions during the welcome ceremony at the Sir Dawda Kairaba Jawara International Conference Centre were centered around the importance of the Epiverse initiative and plans for its second phase. ],
  rect[#image("./images/teamb.png", height: 100%),],
  figure(
  image("./images/teamb.png", width: 100%),
  caption: [Dr. Ahmadou Lamin Samateh, the Honourable Minister of Health of The Gambia.],
),
  rect(inset: 8pt, fill: rgb("#10BED2"), width: 100%)[#text(size: 30pt)[“...the development of analytics tools for pandemic preparedness and response is timely and essential ...”.]]
)

```


```{=typst}
// We use `rect` to emphasize the
// area of cells.
>>>>>>> 09cfafa (update openning ceremony section)

#set rect(
  inset: 8pt,
  fill: rgb("e4e5ea"),
  width: 100%,
)

#grid(
  columns: (1fr, 1fr),
  rows: (260pt, 30pt),
  gutter: 0pt,
  figure(
  image("./images/teamb.png", width: 100%),
  caption: [Dr. Bubacarr Bah, Head of Data Science Cluster at MRCG at LSHTM.]
),
  rect[“This is a global initiative and it is about building open-source tools for analysis to transform the way we deliver data science for social good. Our main goal was to change how analytics tools are used in global infectious disease response, moving from ad-hoc approaches to integrated, generalisable and scalable community-driven software.”],
  rect(inset: 14pt, fill: rgb("#10BED2"), width: 100%)[#text(size: 30pt)[This can be one of the picture from Uyi's presentation.]],
  figure(
  image("./images/teamb.png", width: 100%),
  caption: [Dr. Uyi Stewart, Chief Data and Technology Officer.]
)
  
)
```
 


### Sustainability of Epidemics Analytics Tools

```{=typst}
#lorem(60)
```
### Inclusivity within Epiverse-TRACE Tools

Khairoonisa Foflonker's presentation at the EPIVERSE Summit effectively
demystified inclusivity by highlighting its fundamental principles, the
crucial role of cultural sensitivity and power dynamics, and the need to
move beyond operational EDI towards strategic and transformational
approaches that address systemic barriers and foster a true sense of
belonging within research and work environments. The presentation
encourages critical self-reflection and proactive steps towards building
more inclusive cultures.

### Team Building

```{=typst}

Summary

The thrill of the Kartong Snake Farm to the rhythm of paddles on the River Gambia, our team-building journey blended adventure, culture, and collaboration. This report highlights how these experiences strengthened team members' trust, communication, and camaraderie.

OBJECTIVES OF THE TEAM BUILDING

Build resilience through shared challenges.

Strengthen team connections and foster collaboration.

Encourage trust and effective communication.



ACTIVIES

Conference Dinner: An Evening of Connection

The conference dinner set the tone for the summit, with teams sharing stories over traditional dishes like Benachin. Informal conversations sparked ideas that carried into the days ahead.

Kartong Snake Farm Visit: Facing Fears & Building Trust

At the Kartong Snake Farm, teams confronted fears and embraced curiosity. Handling snakes like pythons became a metaphor for tackling workplace challenges head-on.

Boat Ride & Tanji Bird Reserve: A Journey of Discovery

Where the river meets the ocean, our boat ride to the river-ocean confluence symbolised unity in diversity. At the Tanji Bird Reserve, teams observed over 45 bird species, drawing parallels between ecological harmony and workplace collaboration.

Kayaking: Paddling in Sync

The summit culminated with a 15km kayaking challenge on the River Gambia. Coordinating strokes and maintaining communication mirrored the teamwork required under workplace pressure.


OUTCOMES

Increased Collaboration: Strengthened interpersonal relationships and teamwork.

Enhanced Trust: Facing challenges together improved confidence and trust among team members.

Improved Communication: Effective coordination during activities reinforced the importance of clear communication in the workplace.

CLOSING

This journey was just the beginning. Let’s keep exploring, learning, and growing together. The lessons gained from this experience will continue to inspire teamwork and collaboration in our workplace.
```

### NTDsgit

```{=typst}
#lorem(60)
```

### One Health

```{=typst}
#lorem(60)
```

### Disease Surveillance

```{=typst}
#lorem(60)
```

### Designing Outbreak Analytics Course

```{=typst}

Training is a cornerstone of the Epiverse-TRACE project, ensuring that our advanced analytics packages are recognized and adopted by a broader community. As the project enters its second phase, the focus shifts towards developing and delivering structured courses. Training within Epiverse-TRACE is facilitated through a variety of resources, including showcases, case-studies, how-to guides,  tutorials, and the Epi Training Kit (#link("https://epiverse-trace.github.io/epi-training-kit/index-EN.html")[EpiTkit]).

During the final day of the summit, participants shared insights on designing an in-person data-centered outbreak analytics course aimed at training and teaching outbreak analysis as well as on the translation and adaptation of the Epi Training Kit materials for  African context. The discussion also reflected on lessons learned from previous training sessions, identified existing gaps, and explored strategies to address them.
In this session, the training team presented the pre-summit training report along with its feedback (see #link("https://zenodo.org/records/14946723")[Pre-summit Training report]).

 We also discussed strategies for implementing training in the project's second phase, including the EpiTkit modules as part of comprehensive training in TRACE-LAC for Latin America and the LSHTM-MRCG plans for delivering training courses in Africa. 
The discussion centered on four key aspects of training: content, audience, cultural adaptation, and assessment. Participants, divided into five groups, responded to targeted questions within each aspect. Their insights were collected and summarized in the following table.
```

::: {.block fill="luma(610)" inset="12pt" radius="20pt"}

## Contents

1.  Are there any emerging infectious diseases or health challenges in
    Africa that you think should be prioritized in the content? Can you
    provide an example of a specific case that should be included?

Africa faces a range of emerging and re-emerging infectious diseases,
vector-borne diseases, and non-communicable health challenges. Key
examples include Ebola, Mpox, HIV, Malaria, Chikungunya, Dengue, Marburg
virus disease, and cervical cancer caused by HPV.

2.  What do you think is the best structure for tutorial content to make
    it clear, engaging, and easy to follow?

The course should be designed as an integrated, flexible, and adaptable
training program, allowing for self-paced learning while remaining easy
to follow.
:::

::: {.block fill="luma(610)" inset="12pt" radius="20pt"}

## Audience

1.  How can we ensure that the material is inclusive and accessible to
    underrepresented groups in the field, such as women, rural
    professionals, or individuals from different cultures or
    backgrounds?

-   Encourage continuous feedback by allowing participants to share
    their insights in person or virtually.
-   Collect anonymous feedback through surveys, crash reports, and
    real-time comments.

2.  What strategies do you recommend for effectively reaching and
    engaging the target audience, especially in diverse African
    contexts?
    -   Provide multiple feedback channels, including discussion forums
        (e.g., Google Forms, Microsoft Forms).
    -   Designate focus groups to gather perspectives from
        underrepresented audiences.
    -   Engage diverse participants through anecdotal insights to ensure
        varied experiences are considered.
    -   Engage with local leaders and prioritize their needs and areas
        of improvement.
:::

::: {.block fill="luma(610)" inset="12pt" radius="20pt"}

## Cultural Adaptation

1.  What cultural considerations should we keep in mind to make the
    materials relevant and relatable for audiences in different African
    countries?

-   Tailor course materials to each training session rather than using a
    one-size-fits-all approach.
-   Recognize regional and national differences—avoid assuming all
    African countries have the same cultural, social, or educational
    contexts.
-   Respect dress codes by considering cultural norms for both men and
    women.
-   Acknowledge religious observances such as Ramadan and Christmas,
    ensuring that training schedules and activities remain inclusive and
    considerate.

2.  How can we ensure that the examples or case studies used in the
    materials avoid being stigmatizing or insensitive, particularly
    regarding cultural or religious considerations?

    -   Incorporate cultural training to raise awareness of diverse
        perspectives Use inclusive language and avoid topics that may
        reinforce ableism, sexism, classism, or transphobia.
    -   Establish a clear code of conduct that upholds respect and
        inclusivity in all course materials.
:::

::: {.block fill="luma(610)" inset="16pt" radius="20pt"}
## Assessment

1.  How can we gather feedback effectively from learners to continuously
    improve the material?

-   Conduct continuous evaluations and surveys to gather structured
    feedback.
-   Incorporate interactive games to engage learners and assess their
    understanding.
-   Use practical exercises where participants apply their knowledge to
    real-world scenarios, reflecting on what they can do with what
    they’ve learned.

2.  What methods do you recommend for evaluating the impact of these
    materials on knowledge and skills development?

    -   Maintain continuous engagement with stakeholders and foster
        communities of interest.
    -   Facilitate long-term discussions through platforms like GitHub
        issues to track feedback and improvements.
    -   Organize group discussions to gather qualitative insights on
        learners' experiences and skill development.
:::

MRCG 
1. Bubacarr Bah 
2. Nuredin Mohammed 
3. Abdoelnaser Degoot 
4. Bankole Ahadzie 
5. Karim Mané 
6. Atta Lowe 
7. Kebba Secka

LSHTM 
1. Adolfo Valle Campos 
2. Adam Kucharski
3. Carmen Tamayo 
4. James Azam
5. Joshua Lambert
6. Sebastian Funk

Pontificia Universidad Javeriana 
1. Andrés Moreno Barbosa
2. Laura Gomez-Bermeo
3. Zulma

Universidad de los Andes 
1. Maria Camila Tavera Cifuentes
2. Natalia Nino

Data.org
1. Chris Hartgerink
2. Diana Fajardo Pulido
3. Maguette Ndong 
4. paul 

WHO
1. Finlay Campbell
:::
